apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdex-app-dev
  labels:
    app: pdex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdex
  template:
    metadata:
      labels:
        app: pdex
    spec:
      containers:
      - name: pdex
        image: acrpdexdev.azurecr.io/pdex:latest-dev
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: pdex-secrets-dev

---
apiVersion: v1
kind: Service
metadata:
  name: pdex-service-dev
spec:
  selector:
    app: pdex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdex-ingress-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev.pdex.gov.bc.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pdex-service-dev
            port:
              number: 80
