name: Test Laravel PDEX in DEV

on:
  push:
    branches:
      - dev
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Use Testing Environment File
        run: cp .env.testing .env


      - name: Ensure Cache Directory Exists
        run: |
          mkdir -p ./bootstrap/cache
          mkdir -p ./storage/framework/cache/data
          mkdir -p ./storage/framework/sessions
          mkdir -p ./storage/framework/views
          chmod -R 777 ./bootstrap/cache
          chmod -R 777 ./storage

      - name: Run composer install
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --verbose

      - name: Prepare Laravel Application
        run: php artisan key:generate

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: php artisan test
